version: "3.9"

services:
  user_db:
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: user_db
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_INITDB_SKIP_TZINFO: "yes"
    volumes:
      - ./init-user-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"

  user-service:
    image: ${REGISTRY_USERNAME}/user-service:${SERVICE_VERSION}
    environment:
      MYSQL_HOST: user_db
      MYSQL_PORT: 3307
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - user_db
    ports:
      - "8080:8080"

  post_db:
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: post_db
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_INITDB_SKIP_TZINFO: "yes"
    volumes:
      - ./init-post-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3308:3306"

  post-service:
    image: ${REGISTRY_USERNAME}/post-service:${SERVICE_VERSION}
    environment:
      MYSQL_HOST: post_db
      MYSQL_PORT: 3308
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      USER_SERVICE_URL: http://user-service:8080
      SERVICE_USER_HOSTNAME: user-service
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    depends_on:
      - post_db
      - user-service
    ports:
      - "8081:8081"
