apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.k8sProgram.userService.replicaCount }}
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
        - name: user-db
          image: {{ .Values.db.userdb.image }}
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: qwerty
              valueFrom:
                secretKeyRef:
                  name: user-db-credential
                  key: password

            - name: MYSQL_DATABASE
              value: user_db
          volumeMounts:
            - name: user-db-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: user-db-init
          emptyDir: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-db-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-db
  template:
    metadata:
      labels:
        app: post-db
    spec:
      containers:
        - name: post-db
          image: {{ .Values.db.postdb.image}}
          ports:
            - containerPort: 3308
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: qwerty
              valueFrom:
                secretKeyRef:
                  name: post-db-credential
                  key: password
            - name: MYSQL_DATABASE
              value: post_db
          volumeMounts:
            - name: post-db-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: post-db-init
          emptyDir: {}
