apiVersion: v1
kind: PersistentVolume
metadata:
  name: post-microservice-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /Users/Santanu_Barua/Documents/assignment/PostMicroserviceSystem/volume
