apiVersion: v1
kind: Service
metadata:
  name: user-db-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: user-db
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: post-db-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: post-db
  ports:
    - name: mysql
      port: 3306
      targetPort: 3308

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: post-service-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: post-api
  ports:
    - name: http
      port: 8081
      targetPort: 8081
