apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config-map
  namespace: k8s-program
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://user-db:3306/user_db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-db-init
  namespace: k8s-program
data:
  create-tables.sql: |
    create database if not exists user_db;
    use user_db;
    create table if not exists user (
        id bigint primary key auto_increment,
        username varchar(255) not null,
        amount varchar(255) not null,
        amount_of_posts varchar(255) not null
      );
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: post-config-map
  namespace: k8s-program
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://post-db:3306/post_db

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: post-db-init
  namespace: k8s-program
data:
  create-tables.sql: |
    create database if not exists post_db;
    use post_db;
    CREATE TABLE IF NOT EXISTS post (
        id BIGINT PRIMARY KEY AUTO_INCREMENT,
        author_id BIGINT NOT NULL,
        text_of_post VARCHAR(255) NOT NULL,
        posted_at DATE NOT NULL
    );