apiVersion: v1
kind: ConfigMap
metadata:
  name: post-config-map
  namespace: k8s-program
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://post-db:3306/post_db

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: post-db-init
  namespace: k8s-program
data:
  create-tables.sql: |
    create database if not exists post_db;
    use post_db;
    CREATE TABLE IF NOT EXISTS post (
        id BIGINT PRIMARY KEY AUTO_INCREMENT,
        author_id BIGINT NOT NULL,
        text_of_post VARCHAR(255) NOT NULL,
        posted_at DATE NOT NULL
    );