apiVersion: v1
kind: Service
metadata:
  name: post-db-service
  namespace: ${DEFAULT_NAMESPACE}
spec:
  type: NodePort
  selector:
    app: post-db
  ports:
    - name: mysql
      port: 3306
      targetPort: 3308
      nodePort: 30001
