apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
  namespace: k8s-program
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post-api
  template:
    metadata:
      labels:
        app: post-api
    spec:
      containers:
        - name: post-api
          image: santanubarua/post-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: post_db
              value: post-db
            - name: MYSQL_PORT
              value: "3308"
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: qwerty
            - name: USER_SERVICE_URL
              value: "http://user-service:8080"
