apiVersion: v1
kind: Service
metadata:
  name: post-service-service
  namespace: ${DEFAULT_NAMESPACE}
spec:
  type: NodePort
  selector:
    app: post-api
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30004
