apiVersion: v1
kind: Secret
metadata:
  name: user-db-credential
  namespace: k8s-program
type: Opaque
data:
  username: "cm9vdA=="
  password: "cXdlcnR5"

---

apiVersion: v1
kind: Secret
metadata:
  name: post-db-credential
  namespace: k8s-program
data:
  username: "cm9vdA=="
  password: "cXdlcnR5"

# Convert username and password into base64 encoding
#  echo -n 'your-username' | base64
#  echo -n 'your-password' | base64
