apiVersion: v1
kind: Service
metadata:
  name: user-db-service
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: user-db
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: post-db-service
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: post-db
  ports:
    - name: mysql
      port: 3306
      targetPort: 3308
      nodePort: 30001

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-service
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30003

---
apiVersion: v1
kind: Service
metadata:
  name: post-service-service
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: post-api
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30004
