apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-db-stateful
  namespace: k8s-program
spec:
  selector:
    matchLabels:
      app: user-db
  serviceName: user-db-service
  replicas: 1
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
        - name: user-db
          image: mysql:8.0.33
          env:
            - name: MYSQL_DATABASE
              value: user_db
            - name: MYSQL_USER
              value: root
              valueFrom:
                secretKeyRef:
                  name: user-db-credential
                  key: username
            - name: MYSQL_PASSWORD
              value: password
              valueFrom:
                secretKeyRef:
                  name: user-db-credential
                  key: password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: user-db-pvc
              mountPath: /var/lib/mysql
            - name: initdb-script
              mountPath: /docker-entrypoint-initdb.d
  volumes:
    - name: user-db-data
      persistentVolumeClaim:
        claimName: user-db-data
    - name: initdb-script
      configMap:
        name: user-db-init
  volumeClaimTemplates:
    - metadata:
        name: user-db-pvc
      spec:
        storageClassName: hostpath
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: post-db
  namespace: k8s-program
spec:
  selector:
    matchLabels:
      app: post-db
  serviceName: post-db-service
  replicas: 1
  template:
    metadata:
      labels:
        app: post-db
    spec:
      containers:
        - name: post-db
          image: mysql:8.0.33
          env:
            - name: MYSQL_DATABASE
              value: post_db
            - name: MYSQL_USER
              value: root
              valueFrom:
                secretKeyRef:
                  name: post-db-credential
                  key: username
            - name: MYSQL_PASSWORD
              value: qwerty
              valueFrom:
                secretKeyRef:
                  name: post-db-credential
                  key: password
          ports:
            - containerPort: 3308
          volumeMounts:
            - name: post-db-pvc
              mountPath: /var/lib/mysql
            - name: initdb-script
              mountPath: /docker-entrypoint-initdb.d
  volumes:
    - name: post-db-data
      persistentVolumeClaim:
        claimName: post-db-data
    - name: initdb-script
      configMap:
        name: post-db-pvc
  volumeClaimTemplates:
    - metadata:
        name: post-db-pvc
      spec:
        storageClassName: hostpath
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
