apiVersion: v1
kind: Secret
metadata:
  name: user-db-credential
  namespace: k8s-program
data:
  username: "cm9vdA=="
  password: "cXdlcnR5"

---

apiVersion: v1
kind: Secret
metadata:
  name: post-db-credential
  namespace: k8s-program
data:
  username: "cm9vdA=="
  password: "cXdlcnR5"