apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: k8s-program
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
        - name: user-api
          image: santanubarua/user-service:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: user_db
            - name: MYSQL_PORT
              value: "3307"
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: qwerty
  volumeClaimTemplates:
    - metadata:
        name: user-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: manual
