apiVersion: v1
kind: Service
metadata:
  name: user-db-service
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: user-db
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      nodePort: 30001
