apiVersion: v1
kind: Service
metadata:
  name: user-service-service
  namespace: ${DEFAULT_NAMESPACE}
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30003
