apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: ${DEFAULT_NAMESPACE}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ${REGISTER_USERNAME}/user-service:2.0.0
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: user_db
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: qwerty
  volumeClaimTemplates:
    - metadata:
        name: user-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: manual
