apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: k8s-program
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
        - name: user-api
          image: santanubarua/user-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: user-db
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: qwerty
  volumeClaimTemplates:
    - metadata:
        name: user-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: manual
